---
# tasks file for logstash
- name: "Download Logstash's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_stack_version }}-x86_64.rpm"
    dest: "/tmp/logstash-{{ logstash_stack_version }}-x86_64.rpm"
  register: download_logstash
  until: download_logstash is succeeded
- name: Install Logstash
  become: true
  yum:
    name: "/tmp/logstash-{{ logstash_stack_version }}-x86_64.rpm"
    state: present        
- name: Configure Logstash
  become: true
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  notify: restart Logstash